# See: https://jekyllrb.com/docs/configuration/
title: AYMED - Almanya Yüksekokulları Mezunlar Derneği - Verein der Hochschulabsolventen Deutschlands
email: aymed@aymed.org
short_name: AYMED
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://aymed.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:

# Not working - check i18n plugin.
languages: ["tr", "en", "de"]
exclude_from_localizations: ["assets", "CNAME"]
defaultLang: tr
languageNames:
  tr: Türkçe
  de: Deutsch
  en: English

collections_dir: content
collections:
  index:
    output: true
    permalink: /:path/
  haberler:
    output: true
    permalink: /:path/
  diger_haberler:
    output: true
    permalink: /:path/
  duyurular:
    output: true
    permalink: /:path/
  etkinlikler:
    output: true
    permalink: /:path/
  pages:
    output: true
    permalink: /:path/
